---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys the bucket and related policy"
Metadata:
  LintSpellExclude:
    - Discngine
    - 3decision
Parameters:
  User:
    Type: String
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  UserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '3decisionPolicyBucket-${AWS::Region}'
      Users:
        - !Ref User
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource: 
              - !GetAtt Bucket.Arn
Outputs:
  BucketName:
    Value: !Ref Bucket